Detector = gg.getFile():match('[^/]+$')
-------------------------------------------------------------------------
Name =  'BypassRevz.lua' -- Type Name For Start Script . If Someone Will Rename It , Then Script Won't Run
-------------------------------------------------------------------------
if Detector == Name then gg.toast(' Terimakasih Kaga di Rename     ')
-------------------------------------------------------------------------
else 
-------------------------------------------------------------------------
Error = 'Jgn Di Rename Coookk!!!!\n\nDont Rename This File Fuvk\n\nFile Aslinya BypassRevz.lua' -- Type Error Message Here 
print(Error) 
return
end 
-------------------------------------------------------------------------
-- Type Your Script all code bellow . if script isnot renamed then script will run .

function split(qqFullString, qqSeparator) local nFindStartIndex = 1 local nSplitIndex = 1 local nSplitArray = {} while true do local nFindLastIndex = string.find(qqFullString, qqSeparator, nFindStartIndex) if not nFindLastIndex then nSplitArray[nSplitIndex] = string.sub(qqFullString, nFindStartIndex, string.len(qqFullString)) break end nSplitArray[nSplitIndex] = string.sub(qqFullString, nFindStartIndex, nFindLastIndex - 1) nFindStartIndex = nFindLastIndex + string.len(qqSeparator) nSplitIndex = nSplitIndex + 1 end return nSplitArray end function xgxc(qqpy, qmxg) for x = 1, #(qmxg) do xgpy = qqpy + qmxg[x]["offset"] xglx = qmxg[x]["type"] xgqq = qmxg[x]["value"] gg.setValues({[1] = {address = xgpy, flags = xglx, value = xgqq}}) xgsl = xgsl + 1 end end function xqmnb(qmnb) gg.clearResults() gg.setRanges(qmnb[1]["memory"]) gg.searchNumber(qmnb[3]["value"], qmnb[3]["type"]) if gg.getResultCount() == 0 then gg.toast(qmnb[2]["name"] .. "Didn't Find Results") else gg.refineNumber(qmnb[3]["value"], qmnb[3]["type"]) gg.refineNumber(qmnb[3]["value"], qmnb[3]["type"]) gg.refineNumber(qmnb[3]["value"], qmnb[3]["type"]) if gg.getResultCount() == 0 then gg.toast(qmnb[2]["name"] .. "Didn't Find Results") else sl = gg.getResults(999999) qq = gg.getResultCount() xgsl = 0 if qq > 999999 then qq = 999999 end for i = 1, qq do pdqq = true for v = 4, #(qmnb) do if pdqq == true then pyqq = {} pyqq[1] = {} pyqq[1].address = sl[i].address + qmnb[v]["offset"] pyqq[1].flags = qmnb[v]["type"] qqpy = gg.getValues(pyqq) pdpd = qmnb[v]["lv"] .. ";" .. qqpy[1].value qqpd = split(pdpd, ";") tzqqpd = qqpd[1] pyqqpd = qqpd[2] if tzqqpd == pyqqpd then pdjg = true pdqq = true else pdjg = false pdqq = false end end end if pdjg == true then qqpy = sl[i].address xgxc(qqpy, qmxg) xgjg = true end end if xgjg == true then gg.toast(qmnb[2]["name"] .. "Found, Results Are Modified" .. xgsl .. "Data Found") else gg.toast(qmnb[2]["name"] .. "Didn't Find Results") end end end end
--配置↑↑↑勿修改，调用方法   xqmnb(qmnb)
function split(qqFullString, qqSeparator) local nFindStartIndex = 1 local nSplitIndex = 1 local nSplitArray = {} while true do local nFindLastIndex = string.find(qqFullString, qqSeparator, nFindStartIndex) if not nFindLastIndex then nSplitArray[nSplitIndex] = string.sub(qqFullString, nFindStartIndex, string.len(qqFullString)) break end nSplitArray[nSplitIndex] = string.sub(qqFullString, nFindStartIndex, nFindLastIndex - 1) nFindStartIndex = nFindLastIndex + string.len(qqSeparator) nSplitIndex = nSplitIndex + 1 end return nSplitArray end function xgxc(qqpy, Loading1) for x = 1, #(Loading1) do xgpy = qqpy + Loading1[x]["address"] xglx = Loading1[x]["flags"] xgqq = Loading1[x]["value"] xgdj = Loading1[x]["freeze"] if xgdj == nil or xgdj == "" then gg.setValues({[1] = {address = xgpy, flags = xglx, value = xgqq}}) else gg.addListItems({[1] = {address = xgpy, flags = xglx, freeze = xgdj, value = xgqq}}) end xgsl = xgsl + 1 xgjg = true end end function LoadingQ(Loading) gg.setRanges(Loading[1]["memory"]) gg.searchNumber(Loading[3]["value"], Loading[3]["flags"]) if gg.getResultCount() == 0 then gg.toast(Loading[2]["Projects"] .. "Load Failed❌") else gg.refineNumber(Loading[3]["value"], Loading[3]["flags"]) gg.refineNumber(Loading[3]["value"], Loading[3]["flags"]) gg.refineNumber(Loading[3]["value"], Loading[3]["flags"]) if gg.getResultCount() == 0 then gg.toast(Loading[2]["Projects"] .. "Load Failed❌") else sl = gg.getResults(999999) qq = gg.getResultCount() xgsl = 0 if qq > 999999 then qq = 999999 end for i = 1, qq do pdqq = true for v = 4, #(Loading) do if pdqq == true then pyqq = {} pyqq[1] = {} pyqq[1].address = sl[i].address + Loading[v]["address"] pyqq[1].flags = Loading[v]["flags"] qqpy = gg.getValues(pyqq) pdpd = Loading[v]["lv"] .. ";" .. qqpy[1].value qqpd = split(pdpd, ";") tzqqpd = qqpd[1] pyqqpd = qqpd[2] if tzqqpd == pyqqpd then pdjg = true pdqq = true else pdjg = false pdqq = false end end end if pdjg == true then qqpy = sl[i].address xgxc(qqpy, Loading1) end end if xgjg == true then 
end end end end
function edit(orig,ret)_om=orig[1].memory or orig[1][1]_ov=orig[3].value or orig[3][1]_on=orig[2].name or orig[2][1]
gg.clearResults()gg.setRanges(_om)gg.searchNumber(_ov,orig[3].type or orig[3][2])qq=gg.getResultCount()if qq<1 then gg.toast(_on.." Didn't Find Results")else sl=gg.getResults(50000)for i=1,qq do ist=true for v=4,#orig do if ist==true and sl[i].value==_ov then cd={{}}cd[1].address=sl[i].address+(orig[v].offset or orig[v][2])cd[1].flags=orig[v].type or orig[v][3]qqpy=gg.getValues(cd)cdlv=orig[v].lv or orig[v][1]cdv=qqpy[1].value if cdlv==cdv then pdjg=true ist=true else pdjg=false ist=false end end end if pdjg==true then qqpy=sl[i].address for x=1,#(ret)do xgpy=qqpy+(ret[x].offset or ret[x][2])xglx=ret[x].type or ret[x][3]xgqq=ret[x].value or ret[x][1]xgdj=ret[x].freeze or ret[x][4]xgsj={{address=xgpy,flags=xglx,value=xgqq}}if xgdj==true then xgsj[1].freeze=xgdj gg.addListItems(xgsj)else gg.setValues(xgsj)end end xgjg=true end end if xgjg==true then gg.toast(_on.." Successfully Found")else gg.toast(_on.." Didn't Find Results")end end end
local app = {}
--设置搜索模式
app.memorySearchMode = function(MEMORY) 
if (MEMORY == 2) then
gg.setRanges(gg.REGION_JAVA_HEAP | gg.REGION_C_HEAP | gg.REGION_C_ALLOC | gg.REGION_C_DATA | gg.REGION_C_BSS | gg.REGION_PPSSPP) 
end 
if (MEMORY == -1) then
gg.setRanges(gg.REGION_VIDEO) 
end 
if (MEMORY == -2) then 
gg.setRanges(gg.REGION_CODE_APP | gg.REGION_CODE_SYS)         
end 
if (MEMORY == 0) then 
gg.setRanges(gg.REGION_ANONYMOUS)
end        
end
function checkType(dataType)	local type 
if dataType =="D" or dataType == "D" then 
type = gg.TYPE_DWORD 
end 
if dataType == "F" then 
type = gg.TYPE_FLOAT 
end 
if dataType == "E" then 
type = gg.TYPE_DOUBLE 
end 
if dataType == "B" or dataType == "B" then 
type =  gg.TYPE_BYTE 
end 
if dataType == "W" or dataType == "W" then 
type = gg.TYPE_WORD os.exit() 
end	
return type 
end
app.memorySearch = function(pkgName, isNewSearch, address, tb, dataType)	
gg.clearResults() 
gg.setVisible(false)	local isSucess = gg.searchNumber(tb[1]["lv"], checkType(dataType), false, gg.SIGN_EQUAL, address, -1);	local t = gg.getResults(9999);	local tab = {}	local data = {}	for i=1, #t do	for j=2, #tb do	tab[j] = {} tab[j].address = t[i].address + tb[j]["offset"] if(tb[j]["type"] == nil) then tab[j].flags = t[i].flags else tab[j].flags = checkType(tb[j]["type"]) end tab = gg.getValues(tab)	if (tab[j].value == tb[j]["lv"]) then data[#data+1] = t[i].address end end	end gg.clearResults() return isSucess, data end app.memoryWrite = function(pkgName, address, value, dataType) gg.setVisible(false)	local t = {}	t[1] ={}	t[1].address = address	t[1].flags = checkType(dataType)	t[1].value = value	return gg.setValues(t) end
GG = {Read,Write} 
function GG.ReadWrite(Read,Writw)TZ = {} dataTZ = Read[1] offset = dataTZ[2] for i=1,#Read do TZA = Read[i] LV = {["lv"] = TZA[1],["offset"] = TZA[2]-offset} table.insert(TZ, i, LV) end app.memorySearchMode(Memory) isSuuess,TUG = app.memorySearch(pkgName, true, 0, TZ, Type) if TUG[1] == nil then  else for ii=1,#TUG do for iii=1,#Write do dataxg = Write[iii] value = dataxg[1] Deviant = dataxg[2] app.memoryWrite(pkgName,TUG[ii]+Deviant-offset,value,Type) end end gg.toast(ID.. "Successfully Found") end end
function SearchWrite(Search, Write, Type)
gg.clearResults()
gg.setVisible(false)
gg.searchNumber(Search[1][1], Type)
local t = gg.getResults(9999)
gg.clearResults()
if t ~= nil then
local r = {}
for j=2, #Search do
for i, v in ipairs(t) do
r[i] = {}
r[i].address = v.address + Search[j][2] - Search[1][2]
r[i].flags = v.flags
end
r = gg.getValues(r)
for i = #t, 1, -1 do
if (tostring(r[i].value) ~= tostring(Search[j][1]) ) then
table.remove(t, i)
table.remove(r, i)
end
end       
end
--写入数据
local r = {}
for i=1, #t do
for j=1, #Write do
r[#r+1] = {}
r[#r].address = t[i].address + Write[j][2] - Search[1][2]
r[#r].flags = t[i].flags
r[#r].value = Write[j][1]
r[#r].freeze = true--冻结的话修改后面加false
end
end
gg.setValues(r)
end
end

 if gg.getTargetPackage() == "com.tencent.ig" or gg.getTargetPackage() == "com.pubg.krmobile" or gg.getTargetPackage() == "com.tencent.igsa"  then
  gg.clearResults()
  else
  print("\nTarget GameGuardian nya Salah cukkk\n")
  os.exit()
  end



gg.alert('####   P E N T I N G   ####\n1. Semua Cheat itu Resikonya Ter BANNED\n2. Kalau RAGU Mending pake Akun 2nd\n3. NO COMPALIN Jika Terbanned\n\n\n~ Tapi disini Ogut coba kasih yang terbaik ~\n\nTETEP MAU LANJUT?', 'TRABAS AJA LAH ANJINKK')
gg.toast("🇮🇩")
gg.sleep(300)
gg.toast("🇮🇩O")
gg.sleep(300)
gg.toast("🇮🇩OP")
gg.sleep(300)
gg.toast("🇮🇩OPE")
gg.sleep(300)
gg.toast("🇮🇩OPEN")
gg.sleep(300)
gg.toast("🇮🇩OPENI")
gg.sleep(300)
gg.toast("🇮🇩OPENIN")
gg.sleep(300)
gg.toast("🇮🇩OPENING")
gg.sleep(300)
gg.toast("🇮🇩OPENING ")
gg.sleep(300)
gg.toast("🇮🇩OPENING D")
gg.sleep(300)
gg.toast("🇮🇩OPENING DU")
gg.sleep(300)
gg.toast("🇮🇩OPENING DUL")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU ")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU B")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU BE")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU BEN")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU BENT")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU BENTA")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU BENTAR")
gg.sleep(300)
gg.toast("🇮🇩OPENING DULU BENTAR🇮🇩")
gg.sleep(50)
gg.toast("🇮🇩OPENING DULU BENTAR🇮🇩")
gg.sleep(50)
gg.toast("🇮🇩OPENING DULU BENTAR🇮🇩")
gg.sleep(1000)
gg.toast("🇮🇩RevzProject🇮🇩")
gg.sleep(500)
gg.toast("🇮🇩RevzProject🇮🇩")
gg.sleep(1100)
gg.alert('Numpang titip Pesan buat Ma frennn\n\n\n H \n A \n R \n B \n E \n Y \n DANCUK ~', 'LANJUT TOT')
gg.sleep(300)

HOME = 1
function HOME()
  MN = gg.choice({
  "1. BYPASS  PUBGM GLOBAL [Lobby]",
  "2. BYPASS  PUBGM KOREA [Lobby] ",
  "~[ M E L E B U H ]~",},nil,"🇮🇩RevzProject🇮🇩")
  if MN == nil then
  else
  
  if MN == 1 then GL() end
  if MN == 2 then KR() end
  if MN == 3 then CLOSE() 
  end
  end
  REVZ = -1
  end
  
  function GL()
gg.toast("🇮🇩")
gg.sleep(300)
gg.toast("🇮🇩R")
gg.sleep(300)
gg.toast("🇮🇩Re")
gg.sleep(300)
gg.toast("🇮🇩Rev")
gg.sleep(300)
gg.toast("🇮🇩Revz")
gg.sleep(300)
gg.toast("🇮🇩RevzP")
gg.sleep(300)
gg.toast("🇮🇩RevzPr")
gg.sleep(300)
gg.toast("🇮🇩RevzPro")
gg.sleep(300)
gg.toast("🇮🇩RevzProj")
gg.sleep(300)
gg.toast("🇮🇩RevzProje")
gg.sleep(300)
gg.toast("🇮🇩RevzProject")
gg.sleep(300)
gg.toast("🇮🇩RevzProject🇮🇩")
gg.sleep(1500)
  gg.clearResults()
  gg.setVisible(false)
  gg.setRanges(gg.REGION_C_ALLOC)
  gg.setVisible(false)
  gg.searchNumber("582749752655872;620137442967552", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.setVisible(false)
  gg.refineNumber("582749752655872", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.setVisible(false)
  gg.editAll("288233678981562368", gg.TYPE_QWORD)
  gg.clearResults()
  gg.setVisible(false)
  gg.searchNumber("565157566611456;566257078239232", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.setVisible(false)
  gg.refineNumber("565157566611456", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.setVisible(false)
  gg.editAll("288233678981562368", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.clearResults()
  gg.setVisible(false)
  gg.searchNumber("562954248388607;578351706144768", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.setVisible(false)
  gg.refineNumber("562954248388607", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.setVisible(false)
  gg.editAll("288233678981562368", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.clearResults()
  gg.setVisible(false)
  gg.searchNumber("577252194516992;288233678981562368", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.setVisible(false)
  gg.refineNumber("577252194516992", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.setVisible(false)
  gg.editAll("288233678981562368", gg.TYPE_QWORD)
  gg.setVisible(false)
  gg.clearResults()
  gg.setVisible(false)
  gg.setRanges(gg.REGION_C_ALLOC)
  gg.setVisible(false)
  gg.searchNumber("131586~135682;131330", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
  gg.setVisible(false)
  gg.refineNumber("135682", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
  gg.getResultsCount()
  gg.setVisible(false)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.setVisible(false)
  gg.editAll("135682", 4)
  gg.addListItems((gg.getResults(28888)))
  gg.clearResults()
  gg.clearList()
  gg.setVisible(false)
  gg.clearResults()
  gg.setVisible(false)
  gg.clearResults()
  gg.clearResults()
  gg.setRanges(gg.REGION_C_ALLOC)
  gg.setVisible(false)
  gg.searchNumber("131586~135682;131330", gg.TYPE_DWORD)
  gg.setVisible(false)
  gg.refineNumber("131586", gg.TYPE_DWORD)
  gg.setVisible(false)
  gg.getResults(50000)
  gg.editAll("67109633", gg.TYPE_DWORD)
  gg.clearResults()
  gg.alert("DAH LAH MALES Dah Selesai")
gg.toast("🇮🇩RevzProject🇮🇩")
  end
  
  
  
  function KR()
  gg.toast("🇮🇩")
gg.sleep(300)
gg.toast("🇮🇩R")
gg.sleep(300)
gg.toast("🇮🇩Re")
gg.sleep(300)
gg.toast("🇮🇩Rev")
gg.sleep(300)
gg.toast("🇮🇩Revz")
gg.sleep(300)
gg.toast("🇮🇩RevzP")
gg.sleep(300)
gg.toast("🇮🇩RevzPr")
gg.sleep(300)
gg.toast("🇮🇩RevzPro")
gg.sleep(300)
gg.toast("🇮🇩RevzProj")
gg.sleep(300)
gg.toast("🇮🇩RevzProje")
gg.sleep(300)
gg.toast("🇮🇩RevzProject")
gg.sleep(300)
gg.toast("🇮🇩RevzProject🇮🇩")
gg.sleep(1500)
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
  os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
  os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
  os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations")
  os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
  os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
  gg.clearList()
  gg.clearResults()
  os.remove(("/data/data/com.tencent.ig/app_crashrecord/1004"))
  os.remove(("/data/data/com.tencent.ig/files/__tsecache.dat"))
  os.remove(("/data/data/com.tencent.ig/files/AdjustAttribution"))
  os.remove(("/data/data/com.tencent.ig/files/AdjustIoActivityState"))
  os.remove(("/data/data/com.tencent.ig/files/AdjustIoPackageQueue"))
  os.remove(("/data/data/com.tencent.ig/files/apm_cc"))
  os.remove(("/data/data/com.tencent.ig/files/AppEventsLogger.persistedevents"))
  os.remove(("/data/data/com.tencent.ig/files/cache.crc.dat"))
  os.remove(("/data/data/com.tencent.ig/files/gcTestConfig.txt"))
  os.remove(("/data/data/com.tencent.ig/files/hawk_data_init"))
  os.remove(("/data/data/com.tencent.ig/files/local_crash_lock"))
  os.remove(("/data/data/com.tencent.ig/files/tersafe.update"))
  os.remove(("/data/data/com.tencent.ig/files/mycpuinfo"))
  os.remove(("/data/data/com.tencent.ig/files/tpnlcache.data"))
  os.remove(("/data/data/com.tencent.ig/files/tss_app_915c.dat"))
  os.remove(("/data/data/com.tencent.ig/files/tss_cs_stat2.dat"))
  os.remove(("/data/data/com.tencent.ig/files/tss_uts_c2.dat"))
  os.remove(("/data/data/com.tencent.ig/files/tss.i.m.dat"))
  os.remove(("/data/data/com.tencent.ig/files/tss_tmp/config2.xml.6dab626b"))
  os.remove(("/data/data/com.tencent.ig/files/tss_tmp/config3.xml"))
  os.remove(("/data/data/com.tencent.ig/files/tss_tmp/mn_cache.dat"))
  os.remove(("/data/data/com.tencent.ig/files/tss_tmp/tss_emu_c2.dat"))
  os.remove(("/data/data/com.tencent.ig/files/tss_tmp/tss.ano2.dat"))
  os.remove(("/storage/emulated/0/tencent/Midas/Log/com.pubg.krmobile/MidasLog.mmap"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/cacheFile.txt"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/cache/GCloud.config"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/vmpcloudconfig.json"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/Epic Games/KeyValueStore.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate/SaveGames/JKGuestRegisterCnt.json"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppBaseConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AudioPluginConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/BuildConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/CustomDeviceList.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceProfiles.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceSwitchers.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/EditorPerProjectUserSettings.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Engine.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Game.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/GameUserSettings.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Hardware.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IMSDKConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Input.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/LogSuppression.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/MidasConfig.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OBHttp.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OpenIDCommand.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/PufferDownloader.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Scalability.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/ServerSwitch.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UAE.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Updater.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserCustom.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserSettings.ini"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/CommonSaveGame_4126599880770857.json"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/LeagueStatue.json"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/loginInfoFile.json"))
  os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/MailPhoneLogin.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4123188938540329.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/playerprefs.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4123188938540329.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/business_res_download_priority_table_new"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/cadge_table"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/dubber_table_ext"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/easy_buy_cfg"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_award_table"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_task_table"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/new_level_task_cover_table"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/social_authorize_config"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/upgrade_parameter"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json"))
os.remove(("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json"))
os.remove(("/data/data/com.tencent.ig/app_crashrecord/1004"))
os.remove(("/data/data/com.tencent.ig/files/__tsecache.dat"))
os.remove(("/data/data/com.tencent.ig/files/AdjustAttribution"))
os.remove(("/data/data/com.tencent.ig/files/AdjustIoActivityState"))
os.remove(("/data/data/com.tencent.ig/files/AdjustIoPackageQueue"))
os.remove(("/data/data/com.tencent.ig/files/apm_cc"))
os.remove(("/data/data/com.tencent.ig/files/AppEventsLogger.persistedevents"))
os.remove(("/data/data/com.tencent.ig/files/cache.crc.dat"))
os.remove(("/data/data/com.tencent.ig/files/gcTestConfig.txt"))
os.remove(("/data/data/com.tencent.ig/files/hawk_data_init"))
os.remove(("/data/data/com.tencent.ig/files/local_crash_lock"))
os.remove(("/data/data/com.tencent.ig/files/tersafe.update"))
os.remove(("/data/data/com.tencent.ig/files/mycpuinfo"))
os.remove(("/data/data/com.tencent.ig/files/tpnlcache.data"))
os.remove(("/data/data/com.tencent.ig/files/tss_app_915c.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_cs_stat2.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_uts_c2.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss.i.m.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/config2.xml.6dab626b"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/config3.xml"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/mn_cache.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/tss_emu_c2.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/tss.ano2.dat"))
os.remove(("/storage/emulated/0/tencent/Midas/Log/com.tencent.ig/MidasLog.mmap"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/cacheFile.txt"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/cache/GCloud.config"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/login-identifier.txt"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/Epic Games/KeyValueStore.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate/SaveGames/JKGuestRegisterCnt.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppBaseConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AudioPluginConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/BuildConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/CustomDeviceList.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceProfiles.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceSwitchers.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/EditorPerProjectUserSettings.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Engine.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Game.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/GameUserSettings.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Hardware.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IMSDKConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Input.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/LogSuppression.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/MidasConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OBHttp.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OpenIDCommand.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/PufferDownloader.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Scalability.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/ServerSwitch.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UAE.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Updater.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserCustom.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserSettings.ini"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/CommonSaveGame_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/LeagueStatue.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/loginInfoFile.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/MailPhoneLogin.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4123188938540329.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/playerprefs.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4123188938540329.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/business_res_download_priority_table_new"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/cadge_table"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/dubber_table_ext"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/easy_buy_cfg"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_award_table"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_task_table"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/new_level_task_cover_table"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/social_authorize_config"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/upgrade_parameter"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json"))
os.remove(("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json"))
os.remove(("/data/data/com.tencent.ig/app_crashrecord/1004"))
os.remove(("/data/data/com.tencent.ig/files/__tsecache.dat"))
os.remove(("/data/data/com.tencent.ig/files/AdjustAttribution"))
os.remove(("/data/data/com.tencent.ig/files/AdjustIoActivityState"))
os.remove(("/data/data/com.tencent.ig/files/AdjustIoPackageQueue"))
os.remove(("/data/data/com.tencent.ig/files/apm_cc"))
os.remove(("/data/data/com.tencent.ig/files/AppEventsLogger.persistedevents"))
os.remove(("/data/data/com.tencent.ig/files/cache.crc.dat"))
os.remove(("/data/data/com.tencent.ig/files/gcTestConfig.txt"))
os.remove(("/data/data/com.tencent.ig/files/hawk_data_init"))
os.remove(("/data/data/com.tencent.ig/files/local_crash_lock"))
os.remove(("/data/data/com.tencent.ig/files/tersafe.update"))
os.remove(("/data/data/com.tencent.ig/files/mycpuinfo"))
os.remove(("/data/data/com.tencent.ig/files/tpnlcache.data"))
os.remove(("/data/data/com.tencent.ig/files/tss_app_915c.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_cs_stat2.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_uts_c2.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss.i.m.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/config2.xml.6dab626b"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/config3.xml"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/mn_cache.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/tss_emu_c2.dat"))
os.remove(("/data/data/com.tencent.ig/files/tss_tmp/tss.ano2.dat"))
os.remove(("/storage/emulated/0/tencent/Midas/Log/com.rekoo.pubgm/MidasLog.mmap"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/cacheFile.txt"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/cache/GCloud.config"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/vmpcloudconfig.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/login-identifier.txt"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/Epic Games/KeyValueStore.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate/SaveGames/JKGuestRegisterCnt.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppBaseConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AudioPluginConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/BuildConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/CustomDeviceList.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceProfiles.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceSwitchers.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/EditorPerProjectUserSettings.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Engine.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Game.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/GameUserSettings.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Hardware.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IMSDKConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Input.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/LogSuppression.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/MidasConfig.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OBHttp.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OpenIDCommand.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/PufferDownloader.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Scalability.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/ServerSwitch.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UAE.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Updater.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserCustom.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserSettings.ini"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/CommonSaveGame_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/LeagueStatue.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/loginInfoFile.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/MailPhoneLogin.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4123188938540329.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/playerprefs.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4123188938540329.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4126599880770857.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/business_res_download_priority_table_new"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/cadge_table"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/dubber_table_ext"))
gg.clearResults()
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/easy_buy_cfg"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_award_table"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_task_table"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/new_level_task_cover_table"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/social_authorize_config"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/upgrade_parameter"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json"))
os.remove(("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json"))
gg.clearResults()
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Anticheat.ini")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Anticheat.ini")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/tbslog")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/ca-bundle.pem")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("133634;134914", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber("133634", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("132098;133635", gg.TYPE_DWORD)
gg.refineNumber("132098", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("4096;135682", gg.TYPE_DWORD)
gg.refineNumber("4096", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("131586", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("131842;132098", gg.TYPE_DWORD)
gg.refineNumber("131842", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("133378;134914", gg.TYPE_DWORD)
gg.refineNumber("133378", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("131331;133634", gg.TYPE_DWORD)
gg.refineNumber("131331", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("133634;134658", gg.TYPE_DWORD)
gg.refineNumber("133634", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("134658;134658", gg.TYPE_DWORD)
gg.refineNumber("134658", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("132098;133635", gg.TYPE_DWORD)
gg.refineNumber("132098", gg.TYPE_DWORD)
gg.getResults(50000)
gg.editAll("131842", gg.TYPE_DWORD)
gg.clearResults()
gg.clearList()
gg.clearResults()
gg.clearList()
gg.clearList()
gg.clearResults()
gg.clearList()
gg.clearResults()
gg.clearList()
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/cache")
gg.clearResults() 
gg.alert("DAH LAH MALES Dah Selesai")
gg.toast("🇮🇩RevzProject🇮🇩")
end
  
  
  
  

function CLOSE()
gg.toast("TANGGUNG ")
gg.sleep(400)
gg.toast("TANGGUNG SEDIKIT ")
gg.sleep(400)
gg.toast("TANGGUNG SEDIKIT KELUAR")
gg.sleep(400)
gg.toast("Yah Keluar didalem")
gg.sleep(250)
gg.toast("Yah Keluar didalem")
gg.sleep(250)
gg.toast("Yah Keluar didalem")
gg.sleep(250)
gg.toast("Yah Keluar didalem")
gg.alert("Tolong Jangan di Decrypt")
  print("subrek Youtube Ogut dong\nRevz Project")
  gg.skipRestoreState()
  os.exit()
  gg.setVisible(true)
  end
  while true do
  if gg.isVisible(true) then
  REVZ = 1
  gg.setVisible(false)
  end
  gg.clearResults()
  if REVZ == 1 then
  HOME()
  end
  end